dpc-sdp/baywatch

baywatch.info.yml, baywatch.install, config/install/password_policy.password_policy.password_policy_sdpa.yml
###Jira Ticket - 
https://digital-engagement.atlassian.net/browse/SDPSUP-1710
=> [SDPSUP-1710] Added update hook to import sdpa password policy.

baywatch.info.yml, baywatch.install, composer.json, config/optional/config_split.config_split.ci.yml, config/optional/config_split.config_split.dev.yml, config/optional/config_split.config_split.local.yml, config/optional/key.key.authenticated_content.yml
https://digital-engagement.atlassian.net/browse/SDPA-4623
1. updates /optional/ folder with new configs
2. adds update hooks for importing new configs
=> [SDPA-4623] centralise config_split and key

baywatch.info.yml, baywatch.install, config/optional/config_split.config_split.dev.yml
https://digital-engagement.atlassian.net/browse/SDPA-4642
the baywatch cannot successfully get enabled in content-together, and there was no error message.
dont use `_tide_import_single_config()` function.
=> SDPA-4642 fixes baywatch installation issue

baywatch.install
Fixed the hook to have the correct way to install the tide_oauth module.
=> [fix-install-hook] Updated hook to correct install function for module.

baywatch.install
https://digital-engagement.atlassian.net/browse/SDPA-5122
1. adds an update hook to install tide_edit_protection module
https://github.com/dpc-sdp/tide_core/pull/231
https://github.com/dpc-sdp/tide_core/pull/235
=> Install tide_edit_protection module

composer.json
Revert the changes that are made for drush update.
=> [revert-drush-updates] Removed changes required for drush update.

baywatch.install
Enabling tide_dashboard submodule from tide_core as a part of the cms_improvement work.
=> [enable tide dashboard] Added update hook to enable tide_dashboard module

baywatch.install, src/BaywatchOperation.php
Cleaned up the code and added update hook work in the Baywatch operation class. So that we can call the update work in both install hook and update hook.
=> [organized-hook] Updated hook to run in intall hook as well.

baywatch.install, src/BaywatchOperation.php
https://digital-engagement.atlassian.net/browse/TVD-789
1. installing `tide_ui_restriction` submodule should be managed by `baywatch`.
=> Enables tide_ui_restriction

baywatch.install, src/BaywatchOperation.php, tests/behat/features/timezone.feature
**JIRA issue:** https://digital-engagement.atlassian.net/browse/DDS-245
1.  Update default timezone on install to `Australia/Melbourne`
2. Add a test for above
Output from [build](https://app.circleci.com/pipelines/github/dpc-sdp/reference-sdp-vic-gov-au/221/workflows/87c3c8d7-3a93-4448-8b30-49360ce016b3/jobs/333) using this version:
=> Set default timezone and add test

baywatch.install, config/optional/key.key.section_io_password.yml, config/optional/purge.logger_channels.yml, config/optional/purge.plugins.yml, config/optional/purge_queuer_coretags.settings.yml, config/optional/section_purger.settings.8714ff77fc.yml, src/BaywatchOperation.php
Changed:
1) Import default Section config on install.
=> [DDS-457] : Add default Section config

baywatch.install, src/BaywatchOperation.php
1. Disable permissions_by_term  except for vicpol and ssp.
=> Disable permissions_by_term module

baywatch.install, src/BaywatchOperation.php
https://digital-engagement.atlassian.net/browse/SDPA-5447
Added updated hook to enable the new tide_spell_checker module for all SDP projects.
tide_core - https://github.com/dpc-sdp/tide_core/pull/296
content-vic testing PR - https://github.com/dpc-sdp/content-vic-gov-au/pull/1325
=> Feature/SDPA-5447 enable tide spell check for sdp projects.

baywatch.install, src/BaywatchOperation.php
**JIRA**
https://digital-engagement.atlassian.net/browse/SDPA-6182
**Change**
- Changes file path to exclude.
**Screenshots**
=> [SDPA-6182] Disable basic auth drupal shield on files.

baywatch.install
https://digital-vic.atlassian.net/browse/SDPAP-6371
Disable tide_event_atdw module
=> [SDPAP-6371] Disable tide_event_atdw

baywatch.install
https://digital-vic.atlassian.net/browse/SRM-496
field and storage should be loaded by its storage object.
=> [SRM-496 Fixes status report error]

baywatch.install, composer.json
Jirra: https://digital-vic.atlassian.net/browse/SDPAP-5915
Remove tide_block_inactive_users module, it is replaced by the tide_user_expire module instead.
=> SDPAP-5915: Remove tide_block_inactive_users module.

baywatch.install, src/BaywatchOperation.php
**Jira:**
https://digital-vic.atlassian.net/browse/SRM-512
https://digital-vic.atlassian.net/browse/SDPAP-6730
**Changes**
1. Remove deprecated `drupal_get_path()` function
=> [SRM-512] SDPAP-6730 Remove deprecated "drupal_get_path()"

baywatch.install, src/BaywatchOperation.php
https://digital-vic.atlassian.net/browse/SDPAP-6400
This module was added as a part of core change to show the site alert for all projects in tide_core. Added in install and update hook to enable the module
=> Added functions to enable tide site alert module for all SDP projects.

baywatch.install
Fixing a quick bug that introduced a duplicate method number.
=> Update install hook number

composer.json
Updated the config_split to newer version which has been released recently and D10 compatible.
=> Updated config_split version.

src/BaywatchOperation.php
https://digital-vic.atlassian.net/browse/SDPAP-8290
Added new and publication content type to content collection.
Created a hook update in [tide_api](https://github.com/dpc-sdp/tide_api/pull/122) to apply the changes to the existent sites.
=> added news and publication to content collection

composer.json
https://www.drupal.org/project/jwt/issues/3298726
This patch is not needed it anymore as a new release has been created for JWT.
=> remove patch from jwt deprecated function
